### PR TITLE
JENKINS-32983: Parsing Maven Invoker results from slave

### PR DESCRIPTION
**Pull request by jcarsique**
First commit (bc8eec7) is only about upgrading to the latest versions and comes along with some formatting (sorry).
The second commit (2a9fc37) contains the fix to allow using that plugin with a build not executed on master.
See https://issues.jenkins-ci.org/browse/JENKINS-32983 for details.

### CODE REVIEW

**Comment by olamy** [comment]
Thanks for the job.
Well it's really hard to read what changes have been applied with all the formatting changes.
This project use those formatting rules http://maven.apache.org/developers/committer-environment.html
Maybe you could use the file for your favorite IDE?
Then that will ease my life for reviewing :-) 
Just let me know.
Thanks!

**Comment by jcarsique** [comment]
For sure, I'll redo the commits with that formatter. Thanks for the reminder.

**Comment by olamy** [comment]
Thanks @jcarsique I agree the format was not defined

**Comment by jcarsique** [comment]
I was a little bit disappointed by the FindBugs report and finally excluded two alleged NPE. Feel free to better fix them.

**Pull request merged**
