### PR TITLE
Moving to SimpleBuildStep implementation

### PR DESCRIPTION
**Pull request by bguerin**

### CODE REVIEW

**Comment by bguerin** [comment]
@olamy Thanks for the merges. May I ask for a release of the plugin ? Thanks !

**Comment by olamy** [comment]
@bguerin sure I will do waiting this first https://github.com/jenkins-infra/repository-permissions-updater/pull/352  :-(

**Comment by bguerin** [comment]
@olamy Great ! Thanks !

**Comment by olamy** [comment]
@bguerin release done!

**Comment by bguerin** [comment]
YEAH !!!!Thanks a lot

**Comment by olamy** [comment]
no worries mate. Enjoy!!

**Pull request merged**
